In [2]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in c:\users\nemoh\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\nemoh\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nemoh\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\nemoh\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\nemoh\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\nemoh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in c:\users\nemoh\anaconda3\lib\site-packages (1.26.4)

In [52]:
import pandas as pd 
import numpy as np
import warnings
import seaborn as sns
import matplotlib.pyplot as plt .
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
from fuzzy,wuzzy import fuzz

In [108]:
df=pd.read_excel('dataset/candyhierarchy2017.xlsx')

In [45]:
from matplotlib import rcParams
rcParams['figure.figsize'] = (16,6)

In [109]:
df

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,...,Capers,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,90314658,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [110]:
df.shape

(2460, 120)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Columns: 120 entries, Internal ID to Click Coordinates (x, y)
dtypes: float64(4), int64(1), object(115)
memory usage: 2.3+ MB

In [112]:
df.duplicated().sum()

0

In [113]:
df.describe()

,Internal ID,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo]
count,2.460000e+03,85.0,1362.0,99.0,67.0
mean,9.028016e+07,1.0,1.0,1.0,1.0
std,7.435532e+03,0.0,0.0,0.0,0.0
min,9.025877e+07,1.0,1.0,1.0,1.0
25%,9.027520e+07,1.0,1.0,1.0,1.0
50%,9.027780e+07,1.0,1.0,1.0,1.0
75%,9.028242e+07,1.0,1.0,1.0,1.0
max,9.031480e+07,1.0,1.0,1.0,1.0

In [53]:
df.isna().sum()

Internal ID                    0
Q1: GOING OUT?               110
Q2: GENDER                    41
Q3: AGE                       84
Q4: COUNTRY                   64
                            ...
Q12: MEDIA [Daily Dish]     2375
Q12: MEDIA [Science]        1098
Q12: MEDIA [ESPN]           2361
Q12: MEDIA [Yahoo]          2393
Click Coordinates (x, y)     855
Length: 120, dtype: int64

In [193]:
df.drop(columns=['Internal ID', 'Q9: OTHER COMMENTS','Unnamed: 113'], inplace=True)

KeyError: "['Internal ID', 'Q9: OTHER COMMENTS', 'Unnamed: 113'] not found in axis"

In [127]:
df

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,Mounds,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,i do not know,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,Mounds,Fruit Stripe Gum,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,NaN,...,NaN,Capers,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Tiny bottles of maple syrup as given out by Cr...,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [130]:
df['Q1: GOING OUT?'].fillna('i do not know',inplace=True)
df

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,Mounds,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,i do not know,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,Mounds,Fruit Stripe Gum,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,NaN,...,NaN,Capers,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Tiny bottles of maple syrup as given out by Cr...,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [132]:
df['Q2: GENDER'].fillna("i didn't want to say",inplace=True)
df

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,i didn't want to say,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,Mounds,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,i do not know,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,Mounds,Fruit Stripe Gum,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,NaN,...,NaN,Capers,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Tiny bottles of maple syrup as given out by Cr...,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [161]:
df['Q3: AGE']=pd.to_numeric(df['Q3: AGE'],errors='coerce')
df[df['Q3: AGE']>80]=np.nan
df[df['Q3: AGE']<5]=np.nan
df['Q3: AGE'].describe()
impute=int(np.round(df['Q3: AGE'].mean()))
df['Q3: AGE'].fillna(impute,inplace=True)

df

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,i didn't want to say,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,Male,44.0,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,Mounds,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,i do not know,Male,49.0,USA,Virginia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,Male,40.0,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,No,Male,23.0,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24.0,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,Mounds,Fruit Stripe Gum,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,No,Female,33.0,USA,New York,MEH,DESPAIR,JOY,NaN,NaN,...,NaN,Capers,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,No,Female,26.0,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Tiny bottles of maple syrup as given out by Cr...,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,No,Male,58.0,Usa,North Carolina,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,No,Female,66.0,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [164]:
df['Q4: COUNTRY'].unique()

array([nan, 'USA ', 'USA', 'us', 'usa', 'canada', 'Canada', 'Us', 'US',
       'Murica', 'United States', 'uk', 'United Kingdom', 'united states',
       'Usa', 'United States ', 'United staes',
       'United States of America', 'UAE', 'England', 'UK', 'canada ',
       'Mexico', 'United states', 'u.s.a.', 'USAUSAUSA', 'america', 35,
       'france', 'United States of America ', 'U.S.A.', 'finland',
       'unhinged states', 'Canada ', 'united states of america',
       'US of A', 'Unites States', 'The United States', 'North Carolina ',
       'Unied States', 'Netherlands', 'germany', 'Europe', 'U S', 'u.s.',
       'U.K. ', 'Costa Rica', 'The United States of America',
       'unite states', 'U.S.', 46, 'cascadia', 'Australia',
       'insanity lately', 'Greece', 'USA? Hard to tell anymore..',
       "'merica", 'usas', 'Pittsburgh', 45, 'United State', 32, 'France',
       'australia', 'Can', 'Canae', 'New York', 'Trumpistan', 'Ireland',
       'United Sates', 'Korea', 'California', 'Japan', 'USa',
       'South africa',
       'I pretend to be from Canada, but I am really from the United States.',
       'Usa ', 'Uk', 'Iceland', 'Germany', 'Canada`', 'Scotland', 'UK ',
       'Denmark', 'United Stated', 'France ', 'Switzerland',
       'Ahem....Amerca', 'UD', 'Scotland ', 'South Korea', 'New Jersey',
       'CANADA', 'Indonesia', 'United ststes', 'The Netherlands',
       'United Statss', 'endland', 'murrika', 'USA! USA! USA!', 'USAA',
       'Alaska', 'united States ', 'soviet canuckistan', 'N. America',
       'Singapore', 'USSA', 'China', 'Taiwan', 'Ireland ', 'hong kong',
       'spain', 'Sweden', 'Hong Kong', 'U.S. ', 'Narnia', 'u s a',
       'United Statea', 'united ststes', 'subscribe to dm4uz3 on youtube',
       'America', 'United kingdom', 'USA USA USA!!!!',
       "I don't know anymore", 'Fear and Loathing'], dtype=object)

In [177]:
df['Q6 | 100 Grand Bar'].fillna("i didn't try it",inplace=True)
df['Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)'].fillna("i didn't try it",inplace=True)
df['Q6 | Any full-sized candy bar'].fillna("i didn't try it",inplace=True)
df['Q6 | Black Jacks'].fillna("i didn't try it",inplace=True)
df['Q6 | Bonkers (the candy)'].fillna("i didn't try it",inplace=True)
df

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,i didn't want to say,42.0,NaN,NaN,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,Male,44.0,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,Mounds,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,i do not know,Male,49.0,USA,Virginia,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,Male,40.0,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,No,Male,23.0,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24.0,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,Mounds,Fruit Stripe Gum,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,No,Female,33.0,USA,New York,MEH,DESPAIR,JOY,i didn't try it,i didn't try it,...,NaN,Capers,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,No,Female,26.0,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Tiny bottles of maple syrup as given out by Cr...,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,No,Male,58.0,Usa,North Carolina,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,No,Female,66.0,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [187]:
df['Q7: JOY OTHER'].fillna(df['Q7: JOY OTHER'].mode()[0],inplace=True)
df['Q8: DESPAIR OTHER'].fillna(df['Q8: DESPAIR OTHER'].mode()[0],inplace=True)
df['Q10: DRESS'].fillna(df['Q10: DRESS'].mode()[0],inplace=True)
df

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,i didn't want to say,42.0,NaN,NaN,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,Almond Joy,Trump,White and gold,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,Male,44.0,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,Mounds,Trump,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,i do not know,Male,49.0,USA,Virginia,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,Almond Joy,Trump,White and gold,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,Male,40.0,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",Trump,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,No,Male,23.0,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,Almond Joy,Trump,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24.0,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,Mounds,Fruit Stripe Gum,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,No,Female,33.0,USA,New York,MEH,DESPAIR,JOY,i didn't try it,i didn't try it,...,Almond Joy,Capers,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,No,Female,26.0,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Tiny bottles of maple syrup as given out by Cr...,Trump,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,No,Male,58.0,Usa,North Carolina,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,Almond Joy,Trump,White and gold,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,No,Female,66.0,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,Almond Joy,Trump,White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [191]:
df['Unnamed: 113'].isna().sum()
df.drop(columns=['Unnamed: 113'],inplace=True)

In [201]:
df['Q10: DRESS'].fillna(df['Q10: DRESS'].mode()[0],inplace=True)
df

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q6 | York Peppermint Patties,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,i didn't want to say,42.0,NaN,NaN,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,NaN
1,No,Male,44.0,usa,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,Mounds,Trump,White and gold,Sunday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(84, 25)"
2,i do not know,Male,49.0,usa,Virginia,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,NaN
3,No,Male,40.0,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ...",Trump,White and gold,Sunday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(75, 23)"
4,No,Male,23.0,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,JOY,Almond Joy,Trump,White and gold,Friday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24.0,usa,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,MEH,Mounds,Fruit Stripe Gum,White and gold,Friday,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,NaN
2456,No,Female,33.0,usa,New York,MEH,DESPAIR,JOY,i didn't try it,i didn't try it,...,JOY,Almond Joy,Capers,Blue and black,Friday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(70, 26)"
2457,No,Female,26.0,usa,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,MEH,Tiny bottles of maple syrup as given out by Cr...,Trump,Blue and black,Friday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(67, 35)"
2458,No,Male,58.0,usa,North Carolina,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,NaN
2459,No,Female,66.0,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,JOY,Almond Joy,Trump,White and gold,Sunday,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(19, 26)"

In [194]:
df['Q11: DAY'].fillna(df['Q11: DAY'].mode()[0],inplace=True)
df

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q6 | York Peppermint Patties,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,i didn't want to say,42.0,NaN,NaN,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,NaN,NaN,NaN,NaN,NaN
1,No,Male,44.0,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,Mounds,Trump,White and gold,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,i do not know,Male,49.0,USA,Virginia,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,NaN,NaN,NaN,NaN,NaN
3,No,Male,40.0,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ...",Trump,White and gold,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,No,Male,23.0,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,JOY,Almond Joy,Trump,White and gold,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24.0,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,MEH,Mounds,Fruit Stripe Gum,White and gold,Friday,NaN,NaN,NaN,NaN,NaN
2456,No,Female,33.0,USA,New York,MEH,DESPAIR,JOY,i didn't try it,i didn't try it,...,JOY,Almond Joy,Capers,Blue and black,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,No,Female,26.0,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,MEH,Tiny bottles of maple syrup as given out by Cr...,Trump,Blue and black,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,No,Male,58.0,Usa,North Carolina,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,NaN,NaN,NaN,NaN,NaN
2459,No,Female,66.0,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,JOY,Almond Joy,Trump,White and gold,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [195]:
df['Q12: MEDIA [Daily Dish]'].fillna("i wouldn't check out one of these websites",inplace=True)
df['Q12: MEDIA [Science]'].fillna("i wouldn't check out one of these websites",inplace=True)
df['Q12: MEDIA [ESPN]'].fillna("i wouldn't check out one of these websites",inplace=True)
df['Q12: MEDIA [Yahoo]'].fillna("i wouldn't check out one of these websites",inplace=True)
df

C:\Users\nemoh\AppData\Local\Temp\ipykernel_15876\3325664036.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'i wouldn't check out one of these websites' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Q12: MEDIA [Daily Dish]'].fillna("i wouldn't check out one of these websites",inplace=True)
C:\Users\nemoh\AppData\Local\Temp\ipykernel_15876\3325664036.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'i wouldn't check out one of these websites' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Q12: MEDIA [Science]'].fillna("i wouldn't check out one of these websites",inplace=True)
C:\Users\nemoh\AppData\Local\Temp\ipykernel_15876\3325664036.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'i wouldn't check out one of these websites' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Q12: MEDIA [ESPN]'].fillna("i wouldn't check out one of these websites",inplace=True)
C:\Users\nemoh\AppData\Local\Temp\ipykernel_15876\3325664036.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'i wouldn't check out one of these websites' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Q12: MEDIA [Yahoo]'].fillna("i wouldn't check out one of these websites",inplace=True)

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q6 | York Peppermint Patties,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,i do not know,i didn't want to say,42.0,NaN,NaN,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,NaN
1,No,Male,44.0,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,Mounds,Trump,White and gold,Sunday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(84, 25)"
2,i do not know,Male,49.0,USA,Virginia,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,NaN
3,No,Male,40.0,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ...",Trump,White and gold,Sunday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(75, 23)"
4,No,Male,23.0,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,JOY,Almond Joy,Trump,White and gold,Friday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,No,Male,24.0,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,MEH,Mounds,Fruit Stripe Gum,White and gold,Friday,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,NaN
2456,No,Female,33.0,USA,New York,MEH,DESPAIR,JOY,i didn't try it,i didn't try it,...,JOY,Almond Joy,Capers,Blue and black,Friday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(70, 26)"
2457,No,Female,26.0,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,MEH,Tiny bottles of maple syrup as given out by Cr...,Trump,Blue and black,Friday,i wouldn't check out one of these websites,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(67, 35)"
2458,No,Male,58.0,Usa,North Carolina,i didn't try it,i didn't try it,i didn't try it,i didn't try it,i didn't try it,...,NaN,Almond Joy,Trump,White and gold,Friday,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,NaN
2459,No,Female,66.0,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,JOY,Almond Joy,Trump,White and gold,Sunday,1.0,i wouldn't check out one of these websites,i wouldn't check out one of these websites,i wouldn't check out one of these websites,"(19, 26)"